"""Topic templates for the synthetic demo stream (customer feedback for a fictional delivery app)."""

from __future__ import annotations

SLOTS: dict[str, list[str]] = {
    "plan": ["Plus", "Premium", "Family", "annual", "monthly"],
    "amount": ["$12.99", "$24.50", "$9.99", "$49", "$31.20"],
    "phone": ["iPhone 15", "Pixel 8", "Galaxy S23", "iPad", "OnePlus 12"],
    "os": ["iOS 18", "Android 15", "the latest update", "version 7.2"],
    "store": ["FreshMart", "the corner bakery", "Pizza Palace", "GreenLeaf", "Sushi Go"],
    "item": ["milk", "the salad", "my drinks", "the sauce", "half the order", "the dessert"],
    "minutes": ["45 minutes", "an hour", "90 minutes", "two hours", "40 minutes"],
    "code": ["SAVE20", "WELCOME10", "FALL25", "FREESHIP"],
    "city": ["Austin", "Denver", "Portland", "Chicago", "Boston"],
}

# Each topic: id, templates. Templates use {slot} names from SLOTS.
TOPICS: dict[str, list[str]] = {
    "double_charge": [
        "I was charged twice for my {plan} subscription this month",
        "Double charge on my card for {amount}, please refund one of them",
        "My bank shows two identical payments of {amount} from you",
        "You billed me two times for the same {plan} renewal",
        "Got charged {amount} twice today for a single order",
        "Why are there duplicate charges on my statement for {amount}?",
        "Payment went through twice and I only placed one order",
        "Charged twice for the {plan} plan, need one charge reversed",
    ],
    "login_loop": [
        "The app keeps logging me out every few minutes on my {phone}",
        "Stuck in a login loop after updating to {os}",
        "I enter my password and it sends me right back to the sign in screen",
        "Can't stay signed in, it asks me to log in again constantly",
        "Login page refreshes endlessly on my {phone}",
        "Every time I open the app I'm signed out again",
        "After {os} the app won't keep me logged in",
        "Sign in works then immediately kicks me back to the login screen",
    ],
    "late_delivery": [
        "My order from {store} arrived {minutes} late",
        "Delivery took {minutes} longer than the estimate",
        "Driver was {minutes} late and the food was cold",
        "The ETA kept moving and my order showed up {minutes} after it was promised",
        "Waited {minutes} past the delivery window for {store}",
        "Order was supposed to arrive at noon, came {minutes} late",
        "Extremely late delivery again, {minutes} behind schedule",
        "Why does every order from {store} show up {minutes} late?",
    ],
    "missing_items": [
        "My order from {store} was missing {item}",
        "Bag arrived without {item} even though I paid for it",
        "{item} was not in the delivery, please refund",
        "Half my order was missing, no {item} at all",
        "Received the order but {item} was left out",
        "Items missing from my {store} delivery: {item}",
        "They forgot {item} again in my order",
        "Paid for {item} but it never came in the bag",
    ],
    "promo_code": [
        "Promo code {code} says it's invalid at checkout",
        "The {code} discount isn't applying to my order",
        "Coupon {code} doesn't work even though it's not expired",
        "Tried {code} three times and it keeps getting rejected",
        "Your email said use {code} but the app says code not valid",
        "Discount code {code} removes itself when I place the order",
        "Checkout ignores the {code} promo",
        "Why won't {code} apply to my cart?",
    ],
    "app_crash": [
        "App crashes as soon as I open it on my {phone}",
        "Since {os} the app closes immediately on launch",
        "Keeps crashing when I tap on the cart",
        "The app force closes every time I try to check out",
        "Crashes on startup, can't use it at all on {phone}",
        "App freezes and then crashes when I search for {store}",
        "Constant crashes after the update to {os}",
        "The app just quits when I open my order history",
    ],
    "refund_delay": [
        "Still waiting on my refund of {amount} from two weeks ago",
        "Refund was approved but I haven't received {amount} yet",
        "Where is my refund? It's been 10 days",
        "You promised a refund in 3 days, it's been two weeks",
        "My {amount} refund still hasn't shown up on my card",
        "Refund status says processed but no money back",
        "How long does a refund take? Waiting on {amount}",
        "Never got the refund for my cancelled order",
    ],
    "driver_rude": [
        "The driver was extremely rude to me at the door",
        "Courier yelled at me because the building was hard to find",
        "Delivery person was disrespectful and threw the bag",
        "Driver was rude on the phone and hung up on me",
        "Very unprofessional driver, swore at me",
        "The courier was aggressive when I asked about {item}",
        "Rude driver refused to come to my apartment door",
        "Your driver was condescending and rude",
    ],
    "address_bug": [
        "The app won't save my new delivery address",
        "Address autocomplete puts the pin in the wrong place in {city}",
        "It keeps changing my address back to my old one",
        "Can't add an apartment number to my address",
        "Map pin is a block away from my actual address in {city}",
        "Saved addresses disappeared after the update",
        "Delivery address field resets every time I check out",
        "App says my {city} address is outside the delivery area but it isn't",
    ],
    "notification_spam": [
        "I'm getting way too many push notifications",
        "Turned off promos but still get marketing notifications",
        "Notifications at 2am about deals, please stop",
        "The app sends me five promo alerts a day",
        "Can't disable promotional push notifications",
        "Getting spammed with notifications about {store}",
        "Unsubscribed from emails but the push spam continues",
        "Too many notifications, the settings toggle does nothing",
    ],
    "card_declined": [
        "My card keeps getting declined but it works everywhere else",
        "Payment failed with error code 402 on a valid card",
        "Card declined at checkout even with enough balance",
        "Can't add my credit card, it says payment method invalid",
        "Apple Pay fails every time I try to pay",
        "Checkout says payment declined for my {amount} order",
        "Valid card rejected repeatedly by your payment page",
        "Payment error when placing order, card is fine",
    ],
    "cold_food": [
        "Food from {store} arrived cold",
        "Everything was lukewarm when it got here",
        "My pizza was ice cold on arrival",
        "The soup was cold and the fries were soggy",
        "Hot food arrived completely cold again",
        "Order from {store} was cold, not acceptable",
        "Food temperature was terrible, all cold",
        "Cold meal, clearly sat somewhere for a long time",
    ],
}

NOISE: list[str] = [
    "Do you deliver to the airport?",
    "How do I change my profile picture?",
    "Love the new dark mode!",
    "Can I schedule an order for next week?",
    "Is there a student discount?",
    "What are your customer service hours?",
    "Please add more vegan restaurants",
    "How do I delete my account?",
    "The new logo looks great",
    "Can I tip in cash?",
    "Do you have gift cards?",
    "How do I become a driver?",
    "Is my data shared with restaurants?",
    "Can I order alcohol through the app?",
    "Where can I find my receipts?",
    "Can I split the bill with a friend?",
    "Please add a reorder button",
    "Is there a web version?",
    "How are delivery fees calculated?",
    "Can I change the language to Spanish?",
    "Does the app work on smart watches?",
    "My cousin recommended you, great service so far",
    "Could you partner with more pharmacies?",
    "What happened to the loyalty points program?",
    "Is there a way to leave delivery instructions for the gate?",
    "Do restaurants see my phone number?",
    "Can I use a company card for work lunches?",
    "Any plans to launch in Canada?",
    "The holiday theme in the app is cute",
    "Can I order for a friend in another city?",
    "Why do some restaurants have minimum order amounts?",
    "Can I pick up instead of delivery?",
    "Is there a dark store near downtown?",
    "Would love a group ordering feature for the office",
    "Can I get paper receipts mailed to me?",
    "How do referral credits work?",
    "Do drivers get the full tip?",
    "Is contactless delivery the default?",
    "Your support chat bot was actually helpful today",
    "Can I rate individual dishes?",
    "Is the app accessible with screen readers?",
    "Will you ever offer grocery subscriptions?",
    "How do I update my email address?",
    "Can I pay with a gift card and credit card together?",
    "Do you offer catering for big events?",
    "Can restaurants see my order history?",
    "The search filters for allergies are great",
    "Please bring back the old home screen layout",
    "Can I save favorite drivers?",
    "Where is your company headquartered?",
]

PREFIXES = ["", "", "", "Hi, ", "Hello, ", "Hey team, ", "URGENT: ", "Ugh. ", "Help! "]
SUFFIXES = [
    "",
    "",
    "",
    " Thanks.",
    " Please help!",
    " This is the second time.",
    " Fix this please.",
    " Very frustrating.",
    " Any update?",
]
