"""Store interface. Engine code talks only to this protocol, so storage is swappable."""

from __future__ import annotations

from collections.abc import Iterable, Iterator
from contextlib import AbstractContextManager
from datetime import datetime
from typing import Protocol

from toolkit.models import Cluster, ClusterStatus, Event, Exemplar, ItemStatus, StoredItem


class Store(Protocol):
    # --- lifecycle -------------------------------------------------------
    def transaction(self) -> AbstractContextManager[None]:
        """All writes inside commit together or not at all. Re-entrant."""
        ...

    def close(self) -> None: ...

    # --- metadata and locks ---------------------------------------------
    def get_meta(self, key: str) -> str | None: ...

    def set_meta(self, key: str, value: str) -> None: ...

    def acquire_lock(self, name: str, owner: str, now: datetime, ttl_seconds: float) -> bool:
        """Take a named lock unless another owner holds an unexpired one."""
        ...

    def release_lock(self, name: str, owner: str) -> None: ...

    # --- items -----------------------------------------------------------
    def existing_item_ids(self, ids: Iterable[str]) -> set[str]: ...

    def add_items(self, items: list[StoredItem]) -> list[StoredItem]:
        """Insert new items, assigning increasing `seq` values; returns the stored records."""
        ...

    def update_items(self, items: list[StoredItem]) -> None:
        """Replace mutable fields (status, cluster_id, locked, score, embedding, model_id)."""
        ...

    def get_item(self, item_id: str) -> StoredItem | None: ...

    def get_items(self, ids: Iterable[str]) -> list[StoredItem]: ...

    def items_by_status(self, status: ItemStatus, after_seq: int = 0) -> list[StoredItem]: ...

    def cluster_items(self, cluster_id: str, limit: int | None = None) -> list[StoredItem]:
        """Members of a cluster, newest event time first."""
        ...

    def count_cluster_items_since(self, cluster_id: str, since: datetime) -> int:
        """Members with event time strictly after `since`."""
        ...

    def count_items_by_status(self) -> dict[ItemStatus, int]: ...

    def iter_items(self, batch_size: int = 1000) -> Iterator[StoredItem]: ...

    def max_item_seq(self) -> int: ...

    # --- clusters --------------------------------------------------------
    def add_cluster(self, cluster: Cluster, exemplars: list[Exemplar]) -> None: ...

    def update_cluster(self, cluster: Cluster) -> None: ...

    def get_cluster(self, cluster_id: str) -> Cluster | None: ...

    def list_clusters(self, statuses: Iterable[ClusterStatus] | None = None) -> list[Cluster]:
        """Clusters ordered by opened_at then id."""
        ...

    def get_exemplars(self, cluster_id: str) -> list[Exemplar]: ...

    def set_exemplars(self, cluster_id: str, exemplars: list[Exemplar]) -> None: ...

    def add_no_merge(self, a: str, b: str) -> None: ...

    def no_merge_pairs(self) -> set[frozenset[str]]: ...

    # --- events ----------------------------------------------------------
    def append_events(self, events: list[Event]) -> list[Event]:
        """Persist events, assigning increasing `seq` values; returns the stored records."""
        ...

    def list_events(self, after_seq: int = 0, limit: int | None = None) -> list[Event]: ...
